CREATE OR REPLACE VIEW md_cota.pl_quota_view AS
SELECT qu.quota_id,
    qu.quota_code,
    qu.quota_number,
    qu.check_digit,
    gr.group_code,
    qu.external_reference,
    qu.total_installments,
    qu.version_id,
    qu.contract_number,
    qu.is_contemplated,
    qu.is_multiple_ownership,
    qu.contemplation_date,
    qu.administrator_fee,
    qu.insurance_fee,
    qu.fund_reservation_fee,
    qu.acquisition_date,
    qu.cancel_date,
    qu.info_date AS quota_info_date,
    qst.quota_status_type_code,
    qst.quota_status_type_desc,
    qsc.quota_status_cat_code,
    qsc.quota_status_cat_desc,
    qhd.old_quota_number,
    qhd.old_digit,
    qhd.quota_plan,
    qhd.installments_paid_number,
    qhd.overdue_installments_number,
    qhd.overdue_percentage,
    qhd.per_amount_paid,
    qhd.per_mutual_fund_paid,
    qhd.per_reserve_fund_paid,
    qhd.per_adm_paid,
    qhd.per_subscription_paid,
    qhd.per_mutual_fund_to_pay,
    qhd.per_reserve_fund_to_pay,
    qhd.per_adm_to_pay,
    qhd.per_subscription_to_pay,
    qhd.per_insurance_to_pay,
    qhd.per_install_diff_to_pay,
    qhd.per_total_amount_to_pay,
    qhd.amnt_mutual_fund_to_pay,
    qhd.amnt_reserve_fund_to_pay,
    qhd.amnt_adm_to_pay,
    qhd.amnt_subscription_to_pay,
    qhd.amnt_insurance_to_pay,
    qhd.amnt_fine_to_pay,
    qhd.amnt_interest_to_pay,
    qhd.amnt_others_to_pay,
    qhd.amnt_install_diff_to_pay,
    qhd.amnt_to_pay,
    qhd.quitter_assembly_number,
    qhd.cancelled_assembly_number,
    qhd.adjustment_date,
    qhd.current_assembly_date,
    qhd.current_assembly_number,
    qhd.asset_adm_code,
    qhd.asset_description,
    qhd.asset_value,
    qhd.info_date AS quota_history_info_date,
    sst.asset_type_code,
    sst.asset_type_code_ext,
    sst.asset_type_desc,
    qor.quota_origin_code,
    qor.quota_origin_desc,
    adm.administrator_code,
    adm.administrator_desc,
    gr.group_deadline,
    gr.group_start_date,
    gr.group_closing_date,
    gr.per_max_embedded_bid,
    gr.next_adjustment_date,
    gr.current_assembly_date AS grp_current_assembly_date,
    gr.current_assembly_number AS grp_current_assembly_number,
    qu.first_assembly_number,
    qu.created_at quota_created_at,
    qu.modified_at quota_modified_at
   FROM md_cota.pl_quota qu
     JOIN md_cota.pl_quota_status_type qst ON qst.quota_status_type_id = qu.quota_status_type_id
     JOIN md_cota.pl_quota_status_cat qsc ON qsc.quota_status_cat_id = qst.quota_status_cat_id
     JOIN md_cota.pl_quota_history_detail qhd ON qhd.quota_id = qu.quota_id
     JOIN md_cota.pl_quota_origin qor ON qor.quota_origin_id = qu.quota_origin_id
     JOIN md_cota.pl_administrator adm ON adm.administrator_id = qu.administrator_id
     JOIN md_cota.pl_group gr ON gr.group_id = qu.group_id
     JOIN md_cota.pl_asset_type sst ON sst.asset_type_id = qhd.asset_type_id
  WHERE qu.is_deleted IS FALSE AND qst.is_deleted IS FALSE AND qsc.is_deleted IS FALSE AND qhd.is_deleted IS FALSE AND qor.is_deleted IS FALSE AND adm.is_deleted IS FALSE AND gr.is_deleted IS FALSE AND qhd.valid_to IS NULL
  ORDER BY qu.quota_id;
