AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  fromassetportfoliofiletostagerawvolkswagen:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: from_asset_portfolio_file_to_stage_raw_volkswagen
      Role: arn:aws:iam::824514423659:role/AWSGlueAdminAcess
      Command:
        Name: pythonshell
        ScriptLocation: "etl/volkswagen/from_asset_portfolio_file_to_stage_raw.py"
      DefaultArguments:
        --job-language: "python"
        --extra-py-files: "etl/volkswagen/from_asset_portfolio_file_to_stage_raw.py"
      #  --key1: "BUCKET_BAZAR"
      #  --value1: "sftp-internal-archives-adms-sandbox"
        --key2: "--JOB_NAME"
        --value2: "from_asset_portfolio_file_to_stage_raw_volkswagen"
      #  --key3: "--WORKFLOW_NAME"
      #  --value3: "md-cota-from-asset-portfolio-file-to-stage-raw-volks"
        --key4: "--additional-python-modules"
        --value4: "psycopg2-binary,unidecode"
      #  --key5: "--event_bus_name"
      #  --value5: "md-sandbox"
      AllocatedCapacity: 0.0625 # Equivalente a 1/16DPU
      Timeout: 300 # Job timeout em minutos
      MaxRetries: 1 # Número de retentativas
      GlueVersion: '1.0' # Versão do Glue
      MaxCapacity: 0.0625 # Capacidade máxima

Outputs:
  MyGlueJobOutput:
    Description: "Glue Job ARN"
    Value: !Ref fromassetportfoliofiletostagerawvolkswagen