AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda


Globals:
  Function:
    MemorySize: 512
    Runtime: python3.9

Parameters:
  APIRootPath:
    Type: String
    Description: The URL prefix for endpoints in API Gateway.
    Default: '/'

  StagingDatabase:
    Type: String
    Description: The name of MD Cota PostgreSQL Database.

  StagingSchema:
    Type: String
    Description: The Database Schema name for quotas raw data.

  MDCotaSchema:
    Type: String
    Description: The Database Schema name for standardized data in MD Cota DB.

  StagingHost:
    Type: String
    Description: The Host of MD Cota PostgreSQL Database.

  StagingPort:
    Type: Number
    Description: The Port of MD Cota PostgreSQL Database.

  StagingUser:
    Type: String
    Description: The User of MD Cota PostgreSQL Database.

  StagingPassword:
    Type: String
    Description: The Password of MD Cota PostgreSQL Database.

  BeeReaderLambdaName:
    Type: String
    Description: Name of the Beereader lambda function to be invoked.

  BPMWebhookURL:
    Type: String
    Description: URL for BPM confirmation Webhook.

  BPMWebhookToken:
    Type: String
    Description: Authentication token for BPM confirmation Webhook.

  SourceBucket:
    Type: String
    Description: S# Bucket where to access ADMs extracts received from email.

  CubeesUrl:
    Type: String
    Description: Cubees endpoint

  CubeesApiKey:
    Type: String
    Description: Cubees api key for authentication

  AppName:
    Type: String
    Description: Name of each application

  DynamoEnv:
    Type: String
    Description: Define connection method to use with boto3 for DynamoDB.

  SantanderFlowLambdaName:
    Type: String
    Description: Name of the Lambda to be invoked, responsible for process Santander webhook events.

  ConsorcieiAPIURL:
    Type: String
    Description: URL for Consorciei API.

  ConsorcieiAPIToken:
    Type: String
    Description: Authentication token for Consorciei API.

  QuotaCreationLambdaName:
    Type: String
    Description: Name of the Quota Cretaion lambda function to be invoked.

  CubeesCustomerLambdaName:
    Type: String
    Description: Name of the Cubees Customer lambda function to be invoked.

  CompanyBondLambdaName:
    Type: String
    Description: Name of the Company Bond lambda function to be invoked.

  LifeProofLinkLambdaName:
    Type: String
    Description: Name of the Life Proof Link Sender lambda function to be invoked.

  SecretNameEmail:
    Type: String
    Description: Name of the secret to get the emails for wallet request to ADMs

  BucketTemplates:
    Type: String
    Description: Name of the bucket tp get HTML templates for sending emails.


Resources:

  ApiGatewayEndpoint:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: GatewayAuthorization

  MDCotaAPI:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      FunctionName: md-cota
      CodeUri: src
      Handler: api.handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_ROOT_PATH: !Ref APIRootPath
          STAGING_DATABASE: !Ref StagingDatabase
          STAGING_SCHEMA: !Ref StagingSchema
          MD_COTA_SCHEMA: !Ref MDCotaSchema
          STAGING_HOST: !Ref StagingHost
          STAGING_PORT: !Ref StagingPort
          STAGING_USER: !Ref StagingUser
          STAGING_PASSWORD: !Ref StagingPassword
          BPM_WEBHOOK_URL: !Ref BPMWebhookURL
          BPM_WEBHOOK_TOKEN: !Ref BPMWebhookToken
          APP_NAME: !Ref AppName
      Events:
        OpenAPIDocs:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Auth:
              ApiKeyRequired: false
            Path: /openapi.json
            Method: get
        Docs:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Auth:
              ApiKeyRequired: false
            Path: /docs
            Method: get
        StagingQuotas:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Path: /staging/quota
            Method: post
        BPMQuota:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Path: /bpm/quota
            Method: post

  MDCotaBeaReader:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-beereader
      CodeUri: src
      Handler: beereader.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGING_DATABASE: !Ref StagingDatabase
          STAGING_SCHEMA: !Ref StagingSchema
          STAGING_HOST: !Ref StagingHost
          STAGING_PORT: !Ref StagingPort
          STAGING_USER: !Ref StagingUser
          STAGING_PASSWORD: !Ref StagingPassword
          BPM_WEBHOOK_URL: !Ref BPMWebhookURL
          BPM_WEBHOOK_TOKEN: !Ref BPMWebhookToken
          APP_NAME: !Ref AppName

  MDCotaBeaReaderInvoke:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-beereader-invoke
      CodeUri: src
      Handler: beereader_invoke.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          BEEREADER_LAMBDA_NAME: !Ref BeeReaderLambdaName
          APP_NAME: !Ref AppName

  MDCotaADMsExtractEmails:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 180
      FunctionName: md-cota-adms-extract-emails
      CodeUri: src
      Handler: adms_extract_emails.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGING_DATABASE: !Ref StagingDatabase
          STAGING_SCHEMA: !Ref StagingSchema
          STAGING_HOST: !Ref StagingHost
          STAGING_PORT: !Ref StagingPort
          STAGING_USER: !Ref StagingUser
          STAGING_PASSWORD: !Ref StagingPassword
          SOURCE_BUCKET: !Ref SourceBucket
          APP_NAME: !Ref AppName

  MDCotaCubeesCustomer:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 180
      FunctionName: cubees_customer
      CodeUri: src
      Handler: cubees_customer.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGING_DATABASE: !Ref StagingDatabase
          MD_COTA_SCHEMA: !Ref MDCotaSchema
          STAGING_HOST: !Ref StagingHost
          STAGING_PORT: !Ref StagingPort
          STAGING_USER: !Ref StagingUser
          STAGING_PASSWORD: !Ref StagingPassword
          CUBEES_URL: !Ref CubeesUrl
          CUBEES_API_KEY: !Ref CubeesApiKey
          APP_NAME: !Ref AppName

  MDCotaQuotaCreationInvoke:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-quota-creation-invoke
      CodeUri: src
      Handler: quota_creation_invoke.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGING_DATABASE: !Ref StagingDatabase
          MD_COTA_SCHEMA: !Ref MDCotaSchema
          STAGING_HOST: !Ref StagingHost
          STAGING_PORT: !Ref StagingPort
          STAGING_USER: !Ref StagingUser
          STAGING_PASSWORD: !Ref StagingPassword
          APP_NAME: !Ref AppName

  MDCotaSantanderWebhook:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-santander-webhook
      CodeUri: src
      Handler: santander_webhook.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_NAME: !Ref AppName
          DYNAMO_ENV: !Ref DynamoEnv
          SANTANDER_FLOW_LAMBDA_NAME: !Ref SantanderFlowLambdaName

  MDCotaSantanderFlow:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-santander-flow
      CodeUri: src
      Handler: santander_flow.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_NAME: !Ref AppName
          BPM_WEBHOOK_URL: !Ref BPMWebhookURL
          BPM_WEBHOOK_TOKEN: !Ref BPMWebhookToken
          STAGING_DATABASE: !Ref StagingDatabase
          MD_COTA_SCHEMA: !Ref MDCotaSchema
          STAGING_HOST: !Ref StagingHost
          STAGING_PORT: !Ref StagingPort
          STAGING_USER: !Ref StagingUser
          STAGING_PASSWORD: !Ref StagingPassword
          CONSORCIEI_API_URL: !Ref ConsorcieiAPIURL
          CONSORCIEI_API_TOKEN: !Ref ConsorcieiAPIToken
          QUOTA_CREATION_LAMBDA_NAME: !Ref QuotaCreationLambdaName
          CUBEES_CUSTOMER_LAMBDA_NAME: !Ref CubeesCustomerLambdaName
          COMPANY_BOND_LAMBDA_NAME: !Ref CompanyBondLambdaName
          LIFE_PROOF_LINK_LAMBDA_NAME: LifeProofLinkLambdaName

  MDCotaCompanyBond:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-company-bond
      CodeUri: src
      Handler: company_bond.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          CUBEES_URL: !Ref CubeesUrl
          CUBEES_API_KEY: !Ref CubeesApiKey
          APP_NAME: !Ref AppName

  MDCotaLifeProofLinkSender:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-life-proof-link-sender
      CodeUri: src
      Handler: life_proof_link_sender.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_NAME: !Ref AppName
          CONSORCIEI_API_URL: !Ref ConsorcieiAPIURL
          CONSORCIEI_API_TOKEN: !Ref ConsorcieiAPIToken
          CUBEES_URL: !Ref CubeesUrl
          CUBEES_API_KEY: !Ref CubeesApiKey
          BPM_WEBHOOK_URL: !Ref BPMWebhookURL

  MDCotaAssetPortfolioEmailsSending:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-asset-portfolio-emails-sending
      CodeUri: src
      Handler: asset_portfolio_emails_sending.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_NAME: !Ref AppName
          SECRET_NAME_EMAIL: !Ref SecretNameEmail
          BUCKET_TEMPLATES: !Ref BucketTemplates

  MDCotaEmailFileExtraction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-email-file-extraction
      CodeUri: src
      Handler: email_file_extraction.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_NAME: !Ref AppName

  MDCotaSftpFileHandler:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      FunctionName: md-cota-sftp-file-handler
      CodeUri: src
      Handler: sftp_file_handler.handler.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          APP_NAME: !Ref AppName


Outputs:
  ApiArn:
    Description: "MD Cota API Lambda Function ARN"
    Value: !GetAtt MDCotaAPI.Arn
  ApiGateway:
    Description: "The URL is:"
    Value: !Sub "https://${ApiGatewayEndpoint}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  ApiKey:
    Description: "You can find your API Key in the AWS console: (Put in the request HEADER as 'x-api-key')"
    Value: !Sub "https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/api-keys/${ApiGatewayEndpointApiKey}"
