name: Deploy Glue Job

on:
  push:
  pull_request:
    types:
      - closed
permissions:
   id-token: write
   contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials from OIDC provider
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::824514423659:role/GitHubAction-AssumeRoleWithAction
        aws-region: us-east-1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build SAM application
      run: sam build

    - name: Deploy SAM application
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides \
          ParameterKey2=Value2 \
          ParameterKey4=Value4 \
         # ParameterKey3=Value3 \
         # ParameterKey1=Value1 \
         # ParameterKey5=Value5