name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    - name: List Directory Contents
      run: ls -l $GITHUB_WORKSPACE

    - name: Terraform Init
      run: |
        cd $GITHUB_WORKSPACE/terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd $GITHUB_WORKSPACE/terraform
        terraform apply -auto-approve

    - name: Build and Push Docker Image
      run: |
        docker build -t nome_da_sua_imagem .
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
        docker tag nome_da_sua_imagem:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/seu_repositorio_ecr:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/seu_repositorio_ecr:latest

    - name: Deploy Complete
      run: echo "Deployment Complete"
